#' Peak Annotation of MSI Data
#'
#' Annotates binned peak lists by matching m/z values in complimentary LC-MS/MS data acquired
#' separately from an MSI experiment. Defaults to matching m/z values between MSI and LC-MS/MS data within 10 mDa.
#'
#' @param pk.list A data frame containing a data frame of processed peaks and processing details created by MSI.detectpeaks().
#' @param an.list A data frame containing annotated MSI peaks matched to a separate LC-MS/MS dataset.
#' @return A filtered data frame and a table written to the disk containing annotated MSI peaks matched to a separate LC-MS/MS dataset.
#' @examples
#' list.d <- MSI.LoadAll(list.p)
#' d.peaks <- MSI.binpeaks(list.d[["Sample.Info"]],list.d[["Data.files"]],d.peaks,TRUE)
#' list.anno <- read.table("annotations.neg.txt",sep = "\t",header = T)
#' MSI.annotate.peaks(d.peaks,list.anno)
#'
#' @export
MSI.annotate.peaks <- function(
  pk.list,
  an.list
  ){
  # Load peak and LC-MS/MS annotation list
  d.peaks <- pk.list
  list.anno <- an.list

  # Extract detected peaks and peak intensities
  list.f <- data.frame(
    "Feature" = Cardinal::features(d.peaks),
    "mz" = Cardinal::mz(d.peaks),
    "Count" = d.peaks@featureData[["count"]],
    "Frequency" = d.peaks@featureData[["freq"]]
  )

  list.anno.filt <- setNames(
    list.anno[!grepl(
      "iSTD",
      list.anno[["Metabolite.name"]]
    ),
    c("Metabolite.name",
      "Adduct.type",
      "Average.Mz",
      "Source"
    )],
    c("Name",
      "Adduct",
      "mz",
      "Source"
    )
  )


  ## Assign IDs based on LC-MS/MS data
  list.f.anno <- setNames(
    dplyr::select(
      fuzzyjoin::fuzzy_join(
        list.f,
        list.anno.filt,
        by = "mz",
        match_fun = ~ abs(.x - .y) < 0.01
      ),
      c("Feature",
        "Source","Name",
        "Adduct",
        "mz.x","mz.y",
        "Count","Frequency"
      )
    ),
    c(
      "Feature",
      "Source","Name","Adduct",
      "mz.timsTOF","mz.LCMS",
      "Count","Frequency"
    )
  )
  list.f.anno <- list.f.anno[!duplicated(list.f.anno),]

  ## Return unknowns
  list.f.unk <- list.f[list.f[-c(list.f.anno$mz.timsTOF),"mz"],]

  ### Save annotation lists
  write.table(
    list.f.anno,
    "data.annotated.neg.txt",
    col.names = T,
    row.names = F,
    sep = "\t"
  )
  write.table(
    list.f.unk,
    "data.unknown.neg.txt",
    col.names = T,
    row.names = F,
    sep = "\t"
  )

  return(
    list(
      "Annotated" = list.f.anno,
      "Unassigned" = list.f.unk
      )
    )

  }





#' Peak Annotation of Binned MSI Data
#'
#' Annotates binned MSI data and filters peaks for removing duplicate matched m/z values in complimentary LC-MS/MS data acquired
#' separately from an MSI experiment.
#'
#' @param path.rds Path to a specific rds file generated by MSI.binpeaks().
#' @param an.list.filt A filtered data frame containing annotated MSI peaks from MSI.annotate.peaks().
#' @return A combined Cardinal MSImagingExperiment containing annotated features for all study samples.
#' @examples
#' list.batch <- list.files()[grepl("processed.b",list.files())]
#' list.d.anno <- setNames(
#'   lapply(
#'     seq.int(
#'       1,
#'       length(list.batch),
#'       1),
#'     function(x)
#'       MSI.data.filter(
#'         list.batch[[x]],
#'         list.annotated[["Annotated"]]
#'         )
#'     ),
#'   c(list.batch)
#'   )
#'
#' ## Combine and save processed data
#' ### Combine
#' if(length(list.batch) > 1) {
#'   d.processed <- do.call(
#'     Cardinal::cbind,
#'     list.d.anno
#'     )
#'   }
#' if(length(list.batch) == 1) {
#'   d.processed <- list.d.anno[[1]]
#'   }
#'
#' ### Verify that all samples have been correctly combined
#' Cardinal::imageData(d.processed)
#' Cardinal::features(d.processed)
#' Cardinal::pixelData(d.processed)
#' Cardinal::run(d.processed)
#' Cardinal::spectra(
#'   d.processed,
#'   "intensity"
#'   )[,1:25]
#'
#' ### Save data
#' saveRDS(
#'   d.processed,
#'   "data.processed.rds"
#'   )
#' gc(reset = T)
#'
#' @export
MSI.data.filter <- function(
    path.rds,
    an.list.filt
  ) {
  ### Load data
  list.d <- readRDS(
    path.rds
  )
  list.f.anno <- an.list.filt

  ### subset by annotation list
  list.sub <- unique(
    list.f.anno[["Feature"]]
    )
  list.d.anno <- setNames(
    lapply(
      list.d,
      function(x)
        x[c(list.sub),]
    ),
    c(
      names(
        list.d
      )
    )
  )

  ### combine samples
  list.d.anno <- do.call(
    Cardinal::cbind,
    list.d.anno
    )

  return(list.d.anno)

}




